services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/go/src/app
    depends_on:
      - postgres
    environment:
      DATABASE_URI: ${DATABASE_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
      ACCRUAL_SYSTEM_ADDRESS: "http://accrual:8080"
      RUN_ADDRESS: ":${APP_PORT}"
    command: air -c .air.toml
  accrual:
    ports:
      - "8081:8080"
    build:
      dockerfile: accrual.Dockerfile

volumes:
  postgres_data: